# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-03 23:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, default='', max_length=70, verbose_name='Prenom')),
                ('last_name', models.CharField(blank=True, default='', max_length=70, verbose_name='Nom')),
                ('username', models.CharField(blank=True, default='', max_length=70, unique=True, verbose_name='Utilisateur')),
                ('full_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Full Name')),
                ('login', models.CharField(blank=True, default='', max_length=150, verbose_name='login')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_staff', models.BooleanField(db_index=True, default=False, verbose_name='Is Staff')),
                ('is_superuser', models.BooleanField(db_index=True, default=False, verbose_name='Is Superuser')),
            ],
            options={
                'ordering': ['-modified'],
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(blank=True, default='', max_length=70, verbose_name='Nom')),
                ('url_categorie', models.CharField(blank=True, default='', max_length=70, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cmde', models.DateTimeField(verbose_name='Date Commande')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_fact', models.CharField(max_length=200, verbose_name='Montant Facture')),
                ('id_cmde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Commande')),
            ],
        ),
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_msg', models.CharField(max_length=200, null=True)),
                ('objet', models.CharField(max_length=200, null=True, verbose_name='Objet')),
                ('contenu', models.TextField(max_length=200, null=True, verbose_name='Contenu')),
                ('tel', models.CharField(max_length=200, null=True, verbose_name='Tel')),
                ('email', models.CharField(max_length=200, null=True, verbose_name='Email')),
                ('date_msg', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Message')),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_produit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_prod', models.CharField(blank=True, default='', max_length=70, verbose_name='Reference')),
                ('des_prod', models.CharField(blank=True, default='', max_length=70, verbose_name='Description')),
                ('prix_prod', models.FloatField(null=True, verbose_name='Prix')),
                ('remise_prod', models.FloatField(null=True, verbose_name='Remise')),
                ('image_prod', models.ImageField(blank=True, upload_to=b'', verbose_name='Image')),
                ('bulletin_analyse', models.ImageField(blank=True, upload_to='polls/static/polls/images', verbose_name='bulletin analyse')),
                ('cat_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('typePerson', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('polls.person',),
        ),
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('typePerson', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('polls.person',),
        ),
        migrations.AddField(
            model_name='panier',
            name='ref_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Produit'),
        ),
        migrations.AddField(
            model_name='commande',
            name='ref_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Produit'),
        ),
        migrations.AddField(
            model_name='person',
            name='groups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AddField(
            model_name='panier',
            name='id_clt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Client'),
        ),
        migrations.AddField(
            model_name='facture',
            name='id_clt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Client'),
        ),
        migrations.AddField(
            model_name='commande',
            name='id_clt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Client'),
        ),
    ]
