# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 21:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email (Utilisateur)')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='Prenom')),
                ('middle_name', models.CharField(blank=True, max_length=30, verbose_name='middle name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Nom')),
                ('is_staff', models.BooleanField(default=True, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(blank=True, default='', max_length=70, verbose_name='Nom')),
                ('url_categorie', models.CharField(blank=True, default='', max_length=70, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200, null=True)),
                ('date_cmde', models.DateTimeField(verbose_name='Date Commande')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_fact', models.CharField(max_length=200, verbose_name='Montant Facture')),
                ('id_cmde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Commande')),
            ],
        ),
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_msg', models.CharField(max_length=200, null=True)),
                ('objet', models.CharField(max_length=200, null=True, verbose_name='Objet')),
                ('contenu', models.TextField(max_length=200, null=True, verbose_name='Contenu')),
                ('tel', models.CharField(max_length=200, null=True, verbose_name='Tel')),
                ('email', models.CharField(max_length=200, null=True, verbose_name='Email')),
                ('date_msg', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Message')),
            ],
        ),
        migrations.CreateModel(
            name='methode_paiement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_methode', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_produit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_prod', models.CharField(blank=True, default='', max_length=70, verbose_name='Reference')),
                ('des_prod', models.CharField(blank=True, default='', max_length=70, verbose_name='Description')),
                ('prix_prod', models.FloatField(null=True, verbose_name='Prix')),
                ('remise_prod', models.FloatField(null=True, verbose_name='Remise')),
                ('image_prod', models.ImageField(blank=True, upload_to=b'', verbose_name='Image')),
                ('bulletin_analyse', models.ImageField(blank=True, upload_to='polls/static/polls/images', verbose_name='bulletin analyse')),
                ('cat_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('typePerson', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('polls.person',),
        ),
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('typePerson', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('polls.person',),
        ),
        migrations.AddField(
            model_name='panier',
            name='ref_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Produit'),
        ),
        migrations.AddField(
            model_name='commande',
            name='meth_paiemet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.methode_paiement'),
        ),
        migrations.AddField(
            model_name='commande',
            name='ref_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Produit'),
        ),
        migrations.AddField(
            model_name='person',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='person',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='panier',
            name='id_clt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Client'),
        ),
        migrations.AddField(
            model_name='facture',
            name='id_clt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Client'),
        ),
        migrations.AddField(
            model_name='commande',
            name='id_clt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Client'),
        ),
    ]
