# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=200)),
                ('url_categorie', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, default='', max_length=70, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, default='', max_length=70, verbose_name='Last Name')),
                ('full_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Full Name')),
                ('login', models.CharField(blank=True, default='', max_length=150, verbose_name='login')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_staff', models.BooleanField(db_index=True, default=False, verbose_name='Is Staff')),
                ('is_superuser', models.BooleanField(db_index=True, default=False, verbose_name='Is Superuser')),
            ],
            options={
                'ordering': ['-modified'],
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cmde', models.DateTimeField()),
                ('id_clt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_fact', models.CharField(max_length=200)),
                ('id_clt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Client')),
                ('id_cmde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Commande')),
            ],
        ),
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_msg', models.CharField(max_length=200, null=True)),
                ('objet', models.CharField(max_length=200, null=True)),
                ('contenu', models.TextField(max_length=200, null=True)),
                ('tel', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('date_msg', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_produit', models.IntegerField()),
                ('id_clt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_prod', models.CharField(max_length=200)),
                ('des_prod', models.CharField(max_length=200)),
                ('prix_prod', models.FloatField(null=True)),
                ('remise_prod', models.FloatField(null=True)),
                ('image_prod', models.ImageField(upload_to='polls/static/polls/images')),
                ('cat_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('probability', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, default='', max_length=70, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, default='', max_length=70, verbose_name='Last Name')),
                ('full_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Full Name')),
                ('login', models.CharField(blank=True, default='', max_length=150, verbose_name='login')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_staff', models.BooleanField(db_index=True, default=False, verbose_name='Is Staff')),
                ('is_superuser', models.BooleanField(db_index=True, default=False, verbose_name='Is Superuser')),
            ],
            options={
                'ordering': ['-modified'],
                'verbose_name_plural': 'Vendeurs',
            },
        ),
        migrations.AddField(
            model_name='panier',
            name='ref_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Produit'),
        ),
        migrations.AddField(
            model_name='commande',
            name='ref_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Produit'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
