# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-28 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AddField(
            model_name='person',
            name='groups',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='id_clt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Client'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='id_clt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Client'),
        ),
        migrations.AlterField(
            model_name='panier',
            name='id_clt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Client'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
