# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-01 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='bulletin_analyse',
            field=models.ImageField(null=True, upload_to='polls/static/polls/images', verbose_name='bulletin_analyse'),
        ),
    ]
