# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-07 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='adresse_facturation',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Adresse Facturation'),
        ),
        migrations.AddField(
            model_name='commande',
            name='adresse_livraison',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Adresse Livraison'),
        ),
    ]
