# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagecontact',
            name='contenu',
            field=models.CharField(max_length=200),
        ),
    ]
