# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-03 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_produit_bulletin_analyse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='bulletin_analyse',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='polls/static/polls/images', verbose_name='bulletin analyse'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produit',
            name='image_prod',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to=b'', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
