# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-14 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160913_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='items',
            field=models.ManyToManyField(to='polls.Facture', verbose_name='Factures'),
        ),
    ]
