# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20160823_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagecontact',
            name='contenu',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
