# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-14 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_commande_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='commande',
        ),
    ]
