# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-18 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_messagecontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prix_prod',
            field=models.FloatField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
