# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-28 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20160828_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='groups',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
