# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-03 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20160903_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image_prod',
            field=models.ImageField(blank=True, upload_to='/static/polls/images', verbose_name='Image'),
        ),
    ]
