# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-14 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_produit_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='items',
            field=models.ManyToManyField(to='polls.Produit', verbose_name='Factures'),
        ),
    ]
