# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-15 05:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20160914_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='N cmde')),
                ('status', models.IntegerField(default=0, verbose_name='Etat de la commande')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Commentaires')),
                ('is_confidential', models.BooleanField(default=False, verbose_name='Confidentielle?')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Urgente?')),
                ('has_problem', models.BooleanField(default=False, verbose_name='Probleme?')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('date_delivered', models.DateTimeField(blank=True, null=True, verbose_name='Date de livraison')),
                ('last_change', models.DateTimeField(auto_now=True, verbose_name='Derniere modification')),
            ],
            options={
                'ordering': ('status', '-date_created', 'provider'),
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
            },
        ),
        migrations.CreateModel(
            name='OrderComplement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom du complement')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Commandee par')),
                ('username_recept', models.CharField(blank=True, max_length=100, null=True, verbose_name='Receptionne par')),
                ('product_id', models.IntegerField(blank=True, null=True, verbose_name='ID produit')),
                ('name', models.CharField(max_length=500, verbose_name='Designation')),
                ('provider', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fournisseur')),
                ('origin', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fournisseur d origine')),
                ('packaging', models.CharField(blank=True, max_length=100, null=True, verbose_name='Conditionnement')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference')),
                ('offer_nb', models.CharField(blank=True, max_length=100, null=True, verbose_name='N Offre')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Type')),
                ('sub_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sous-type')),
                ('nomenclature', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nomenclature')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('cost_type', models.IntegerField(verbose_name='Type de cout')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantite')),
                ('delivered', models.IntegerField(default=0, verbose_name='Quantite a livrer')),
                ('is_confidential', models.BooleanField(default=False, verbose_name='Confidentielle?')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'Item de commande',
                'verbose_name_plural': 'Items de commande',
            },
        ),
        migrations.RemoveField(
            model_name='commande',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='polls.OrderItem', verbose_name='Produits'),
        ),
        migrations.AddField(
            model_name='order',
            name='provider',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='polls.Vendeur', verbose_name='Fournisseur'),
        ),
    ]
