# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-15 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_commande_ref_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='commande_id',
            field=models.CharField(max_length=120),
        ),
    ]
