# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-16 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20160917_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='id_clt',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='ref_prod',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='id_cmde',
        ),
        migrations.DeleteModel(
            name='Commande',
        ),
    ]
