# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-26 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20160917_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='telephone',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vendeur',
            name='telephone',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
