# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-29 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_produit_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='typePerson',
            field=models.CharField(blank=True, default='vendeur', max_length=200),
        ),
        migrations.AlterField(
            model_name='vendeur',
            name='typePerson',
            field=models.CharField(blank=True, default='client', max_length=200),
        ),
    ]
