# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-30 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20160929_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='typePerson',
            field=models.CharField(blank=True, default='client', max_length=200),
        ),
        migrations.AlterField(
            model_name='produit',
            name='des_prod',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='vendeur',
            name='typePerson',
            field=models.CharField(blank=True, default='vendeur', max_length=200),
        ),
    ]
