# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-04 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20160930_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='owner',
            field=models.CharField(blank=True, max_length=70, verbose_name='Proprietaire'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Prenom'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='des_prod',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='owner',
            field=models.CharField(blank=True, max_length=70, verbose_name='Proprietaire'),
        ),
    ]
