# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-16 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='methode_paiement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_methode', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Order',
            new_name='Commande',
        ),
    ]
