# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-16 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20160917_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='commande',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='prix',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='produit',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='quantite',
        ),
    ]
