# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-16 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20160917_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Commande_items', to='polls.Produit'),
        ),
    ]
