# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-16 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20160917_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='address',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='city',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='email',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='commande',
            name='adresse_facturation',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Adresse Facturation'),
        ),
        migrations.AddField(
            model_name='commande',
            name='adresse_livraison',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Adresse Livraison'),
        ),
        migrations.AddField(
            model_name='commande',
            name='owner',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
