# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-16 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20160917_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='owner',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
