# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-28 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderitem_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='owner',
        ),
        migrations.AddField(
            model_name='commande',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=70, verbose_name='Proprietaire'),
        ),
    ]
